theme: jekyll-theme-cayman
project_title: Azure Services Whiteboard Magnets
title: Azure Services Whiteboard Magnets
twitter:
  username: vjirovsky
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /images/usage/social.png
        height: 640
        width: 1280
